spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tuitienteam
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 3332